### ISSUE TITLE
PermissionError: [WinError 5] Access is denied

### ISSUE THREAD

**Issue by AomTheera** [ggafiled/ThaiPersonalCardExtract#4]
How Fix?

**Comment by AomTheera** [comment]
it's a full error if u can help me
Traceback (most recent call last):
  File "E:\FastAPI\FastOcrThNationcard\main.py", line 7, in <module>
    result = reader.extract_front_info("E:/FastAPI/FastOcrThNationcard/front.jpg")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Automate\Vene\Lib\site-packages\ThaiPersonalCardExtract\PersonalCard\PersonalCard.py", line 231, in extract_front_info
    return self.__extractItems()
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Automate\Vene\Lib\site-packages\ThaiPersonalCardExtract\PersonalCard\PersonalCard.py", line 174, in __extractItems
    " ".join(pytesseract.image_to_string(imgCrop, lang=box["lang"].split(",")[0],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Automate\Vene\Lib\site-packages\pytesseract\pytesseract.py", line 423, in image_to_string
    return {
           ^
  File "E:\Automate\Vene\Lib\site-packages\pytesseract\pytesseract.py", line 426, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Automate\Vene\Lib\site-packages\pytesseract\pytesseract.py", line 288, in run_and_get_output
    run_tesseract(**kwargs)
  File "E:\Automate\Vene\Lib\site-packages\pytesseract\pytesseract.py", line 255, in run_tesseract
    proc = subprocess.Popen(cmd_args, **subprocess_args())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nosf3ratu\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Nosf3ratu\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied

**Comment by ggafiled** [comment]
What is IDE tools that you use?
Seems the error message about can’t read your image because don’t have permission on that path.

**Comment by AomTheera** [comment]
ok I can fix it because tesseract_cmd is the wrong path now I have a new question
why when I use extract_back_info when I print result i have respond like this
Card(Identification_Number='', FullNameTH='', PrefixTH='', NameTH='', LastNameTH='', PrefixEN='', NameEN='', LastNameEN='', BirthdayTH='', BirthdayEN='', Religion='', Address='', DateOfIssueTH='', DateOfIssueEN='', DateOfExpiryTH='', DateOfExpiryEN='', LaserCode='')
this is my code:
    reader = PersonalCard(lang="mix", tesseract_cmd="C:\\Program Files\\Tesseract-OCR\\tesseract.exe", sift_rate=50000)
    result = reader.extract_back_info("E:/FastAPI/FastOcrThNationcard/front.jpg")
    print(result)

**Comment by ggafiled** [comment]
Hi 
Kindly try sample image that in test folder to make sure script able to extract data. If the result of this try is work. I think your image might has very large size that we recommend. Or you can increase KEYPOINT value  to cover your image mapping point.

**Comment by AomTheera** [comment]
but your sample image does not have back info

**Comment by ggafiled** [comment]
Please try change LAG from mix to eng
